version: '3'
services:
  frontend:
    # restart service when service fail
    restart: always
    # build Dockerfile in folder /frontend
    build: ./frontend
    # map port local port:container port
    ports:
      - '3000:3000'
    volumes:
    # 1. A volume dedicated to node modules.
      - /app/node_modules
    # 2. Map folder ./frontend from local to /app in container
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    # restart service when service fail
    restart: always
    # build Dockerfile in folder /api
    build: ./api
    # map port local port:container port
    ports:
      - '5050:5050'
    volumes:
      - ./api:/app
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: very-strong-db-password
    volumes:
    # if use - mongodb_data: it will map mongodb_data in linux of docker
    # if use - ./mongodb_data: it will map mongodb_data in windown which is host of docker
      - mongodb_data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
    # server are [mongo:] above
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: very-strong-db-password
    depends_on:
    # it will start mongo-express when mongo start only
      - mongo
# create mongodb_data volume inside linux of docker [docker is linux vm build on windown]
volumes:
  mongodb_data: